DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR
(
    ID         BIGINT IDENTITY PRIMARY KEY,
    FIRSTNAME  VARCHAR(255) NOT NULL,
    LASTNAME   VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255)
);